### ISSUE TITLE
Add deployments and smoke tests to CI

### ISSUE THREAD

**Issue by Ked57** [Zenika/skillZ#10]
We need to think about the deployment, I see two options
 - Clever Cloud: would be much easier and faster to put together since I'm used to it and since everything at Zenika is hosted there it's quite future proof
 - Managed Kubernetes: doesn't have the pros of Clever Cloud but would be nice to learn 😄

**Comment by MailyLehoux** [comment]
We keep Clever Cloud as main deploy tech. We removed Kubernetes on the release : https://github.com/Zenika/skillZ/releases/tag/v2022-09-26 

I close this issue
