### ISSUE TITLE
The button colors are inverted 

### ISSUE THREAD

**Issue by ebriand** [Zenika/skillZ#103]

**Comment by Ked57** [comment]
Are you talking about these buttons ? 
![image](https://user-images.githubusercontent.com/2174111/131510740-c77ac7da-7913-4dd1-a83b-07e2962cd4f7.png)
I know we already talked about this and I feel like swapping colors is even more confusing

**Comment by ebriand** [comment]
In this case, maybe we need to update the templates created by @stephanecohan?

**Comment by jeanphibaconnais** [comment]
Duplicate #66
