### ISSUE TITLE
Add the notion of "capability"

### ISSUE THREAD

**Issue by ebriand** [Zenika/skillZ#104]
A capability is the sum of multiple skills, it can be badges for a user: "architecture" is the sum of multiple skills

**Comment by Ked57** [comment]
Skills wouldn't have to be random though, I think the DT should fix a set of skill that are eligible for this achievement

**Comment by ebriand** [comment]
Exactly, it cannot be random. This is something to create on the CTO side 👍

**Comment by jeanphibaconnais** [comment]
Hello @ZenikAdrien, do you think it's pertinent to keep this issue ?

**Comment by ZenikAdrien** [comment]
Plus d'actualité avec la notion de domaines de compétences
