### ISSUE TITLE
Let the users add some skills to other users

### ISSUE THREAD

**Issue by ebriand** [Zenika/skillZ#105]
The idea is to "recommend" someone on a skill. Why? Sometimes people are not aware that they are skilled in a domain. I think we can also add the possibility to accept (or refuse) a recommended skill.

**Comment by Ked57** [comment]
That sounds sketchy, can you explain ?

**Comment by ebriand** [comment]
I added a description, WDYT?

**Comment by Ked57** [comment]
Ok this makes sense
