### ISSUE TITLE
Add certifications

### ISSUE THREAD

**Issue by ebriand** [Zenika/skillZ#106]
Add the possibility to add a certification on a skill. For example: I know GCP, I love it and I am certified. It can be useful to filter people if they are certified or not for some customers that require certifications.

**Comment by Ked57** [comment]
FYI the displaying part is implemented at least on the homepage if I remember correctly

**Comment by ebriand** [comment]
I added a description ✏️  I'm not sure which display you are referring 🤔

**Comment by Ked57** [comment]
The homepanels, they can display the number of certifications provided they get the data
