### ISSUE TITLE
Delete "Confirm profile" button

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#118]
On "my profile" page, we have a "confirm profile" button. I'm not sure about its utility, cause we can update information directly with an Onclick() event. I think we can remove it

**Comment by benjaminbrgs** [comment]
After looking at this issue, it seems that the confirm button is only a redirection to the homepage.
All user informations are successfully saved without clicking on it, even on a first sign in.

I think we can remove it, what do you think ?
