### ISSUE TITLE
🔐 Authentication for applications

### ISSUE THREAD

**Issue by guillaumeLamanda** [Zenika/skillZ#144]
Hi here :wave: 

Since this app is the official application for skills tracking, but every agency have its own needs (and tools sometimes), it could be great to be able to create automation :robot:  

To be able to interact with Skillz, we need an API. The good news is: we have GraphQL. But there is only one way to authenticate to the API: using OAuth. It's not suitable for automation.  
Is it possible to have some long-live access tokens, dedicated to applications? The GraphQL API is on Hasura, maybe we could generate an Hasura token on demand for thoses needs? 

Thanks :pray:

**Comment by guillaumeLamanda** [comment]
[Another ask for this feature](https://zenika.slack.com/archives/C063LTVU7/p1646231210047359?thread_ts=1646229964.357779&cid=C063LTVU7) :grin:

**Comment by hgwood** [comment]
I can't see why OAuth is not suitable for applications. See also https://zenika.slack.com/archives/C021ASG3K8V/p1646240409675429?thread_ts=1646229437.474109&cid=C021ASG3K8V. I recommend closing this issue.
