### ISSUE TITLE
unitary tests AVA

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#158]
I have different problems to make unit tests with AVA. The project uses React 17: impossible to use Enzyme. Moreover, I can't find a way to call tsx components in AVA test functions. 

I think the best thing would be to do at least the first tests in peer programming, and maybe to consider changing the initial test lib (we tried to do it a few months ago with Mireille, and to use Jest, but we had dependencies problems with Babel). 

So I'm going to leave the tests aside for this project, I could do it when I'm back.

**Comment by Ked57** [comment]
Yes I wouldn't use ava in the front end
Jest is cool, I might be able to help integrating it. There's also Cypress Component testing which I use a lot at the moment, easy to use and runs in the browser

**Comment by jeanphibaconnais** [comment]
I think we can use booth (jest + cypress) : Jest for unit tests and Cyrpress for end to end.
