### ISSUE TITLE
add skill blinking

### ISSUE THREAD

**Issue by eigidi** [Zenika/skillZ#178]
when adding a skill that does not exist, it is offered the possibility to create a skill. this works one time, then a second time the button doesn't stick, it just blinks.

**Comment by benjaminbrgs** [comment]
hey @eigidi, do you still have this behavior ?
if so, could you precise this issue, with screenshots or steps ?

on my side, I can add skill multiple time and when I try to add a duplicate skill, an error message is displayed.

**Comment by eigidi** [comment]
Hi,

I tested and indeed, the bug is not easy to find :)

The last time I tried, the "Add skill X" button was at the top of the list.
Now it is at the bottom (I almost didn't find it).

When you want to add skill "Joking", you look for it, then you click Add
skill, then you go to the bottom of the list, and you click "Add skill
Joking".
Then, when you want to add a second skill, "Nodding", you click "Add
skill", then for a blimpse, there's a button "Add skill Nodding" which
appears at the top of the list, before appearing at the bottom of the list.
It's really for a millisecond, so I didn't manage to take a screen shot :D


Andreea Dumitrascu
Responsable Recherche et Innovation
Consultante Architecte

Zenika Paris – 10, rue de Milan, 75009 Paris
+33 (0)6 98 42 31 35
<https://links.zenika.com/link/CodeTheWorld>

**Comment by eigidi** [comment]
Glad you managed to understand my description of the blinking bug :))

Andreea Dumitrascu
Responsable Recherche et Innovation
Consultante Architecte

Zenika Paris – 10, rue de Milan, 75009 Paris
+33 (0)6 98 42 31 35
<https://links.zenika.com/link/CodeTheWorld>
