### ISSUE TITLE
Achievements doesn't work anymore

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#191]
I think the new categories doesn't work with the actual achievements. Should we keep this feature ? How should we fix this ? 

![Capture d’écran de 2022-08-31 15-26-37](https://user-images.githubusercontent.com/85115963/187689663-d42150b1-0bda-4d7b-82d9-764e7d2d9d2f.png)

**Comment by ZenikAdrien** [comment]
Fixed by commit ac5b1e5fd7ebe465a92166c566e7dc88b9b33941
