### ISSUE TITLE
Front page loop reload after login

### ISSUE THREAD

**Issue by fredericbarrau** [Zenika/skillZ#200]
MacOS version: 12.5.1
Safari Version:  Version 15.6.1 (17613.3.9.1.16)

Behaviour:
After login, the front page loop-reloads. After a while (3-5 min ?), the loop ends, and the page shows the following message: `Error: Error, Message: Could not verify JWT: JWTIssuedAtFuture`

Network traces of the browser show a redirection loop between skillz.zenika.com and zenika.eu.auth0.com.

Same behaviour using a private window.

**Edit**: same behaviour using Firefox 104.0.2 (64-bit)

Maybe something weird with my Zenika Google Account ?

**Comment by fredericbarrau** [comment]
Stopped the JS using the debugger, the console show the following messages:

```
unreachable code after return statement
[main-da851132ab69310d.js:1:27409](https://skillz.zenika.com/_next/static/chunks/main-da851132ab69310d.js)
Some cookies are misusing the recommended “SameSite“ attribute 3
TypeError: a.User[0] is undefined
    NextJS 30
[framework-5f4595e5518b5600.js:1:82741](https://skillz.zenika.com/_next/static/chunks/framework-5f4595e5518b5600.js)
TypeError: a.User[0] is undefined
    NextJS 30
[main-da851132ab69310d.js:1:17568](https://skillz.zenika.com/_next/static/chunks/main-da851132ab69310d.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [main-da851132ab69310d.js:1:17585](https://skillz.zenika.com/_next/static/chunks/main-da851132ab69310d.js)
The resource at “https://skillz.zenika.com/fonts/Nunito/Nunito-Regular.ttf” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [skillz.zenika.com](https://skillz.zenika.com/)
```

**Comment by fredericbarrau** [comment]
Just to add that I've reproduced this issue on windows / edge as well. Any updates ? 
I saw in #207 that maybe I should "select an agency" ? Where ? How ?

**Comment by MailyLehoux** [comment]
Hi @fredericbarrau , Thanks for your feedback. We have fixed this issue on the last release. It should works now :+1: I'll close this issue. Please tell me if you still have any problem
