### ISSUE TITLE
circles on skills radar are broken when we have to much skills

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#224]
I've noticed this bug in staging env. 

When I add more than 25 skills with 3 and 3 as desire and skill level, the circles with 3 and 2, 2 and 3 ect. disappear 

![Capture d’écran de 2022-09-20 18-19-55](https://user-images.githubusercontent.com/85115963/191313923-6f7f82b0-fcd0-457e-aaef-13fa0fc42baf.png)

On this screen, Angular 7 will disappear in first then Anglais will too..

**Comment by benjaminbrgs** [comment]
I'm waiting before working on this, because it could be fix by : https://github.com/Zenika/skillZ/pull/223
