### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by benjaminbrgs** [Zenika/skillZ#248]
Skillz does not work in HTTP.
We can redirect HTTP to HTTPS and fix this issue in the same time

![image](https://user-images.githubusercontent.com/20949060/193554111-40fafa5b-c841-4121-91e3-89d0e629d4de.png)

**Comment by hgwood** [comment]
J'ai activé le forçage HTTPS au niveau de Clever Cloud. A voir si vous voulez quand même le forcer au niveau de l'application, mais ce n'est pas forcément nécessaire.
