### ISSUE TITLE
Dark mode on loading page

### ISSUE THREAD

**Issue by benjaminbrgs** [Zenika/skillZ#276]
![image](https://user-images.githubusercontent.com/20949060/196379130-82536642-1739-499f-8c47-29d3f6e83457.png)

**Comment by Anuran12** [comment]
@benjaminbrgs  I would like to work on this

**Comment by jeanphibaconnais** [comment]
Hi @Anuran12 , yes of course, thanks for your interest ! I assign you this issue.

**Comment by benjaminbrgs** [comment]
Hi @Anuran12, it looks like you deleted your assignment on this issue. Would you still want to work on this ?

**Comment by Anuran12** [comment]
@benjaminbrgs sorry i am unable to solve that 🙏

**Comment by benjaminbrgs** [comment]
@Anuran12 No worries :) Thanks again for your interest.

**Comment by benjaminbrgs** [comment]
Actually, the dark mode on Loading component already exists. But sometimes, when the DarkMode provider are not fully mounted, the Loading page are displayed without user preferred settings (and therefore without dark mode sets)
