### ISSUE TITLE
Buttons in admin modal

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#326]
The buttons are useless cause we use mutation at each changes. We can refacto and request on a click to update all changes, either we have to delete the buttons. We have to do a choice 😁

What do you think 

![Capture d’écran de 2022-11-09 14-33-24](https://user-images.githubusercontent.com/85115963/200843702-cf19bcfc-92a9-47e3-8a52-49b7d6fec5be.png)

**Comment by benjaminbrgs** [comment]
Actually, both way are good :) I'd say the easiest choice is to remove the update button. It's already working in this way on the profile page.

**Comment by PierreBrethes** [comment]
You can still "save" which topic you modified and as you don't have any buttons now, when the modal is closed, you send the request with all changes at one time. If you still want the idea to regroup all changes in one request

**Comment by ThomG317** [comment]
I don't know the user's needs behind the modal or this issue, but I would say: what do you do with other modals ? Better be consistent from one modal to another to ensure uniformity and avoid unpredictable behavior.

**Comment by benjaminbrgs** [comment]
@PierreBrethes @ThomG317 As the topic is a reused component as well as the category and it's working without save button on profile page, the best way is to remove buttons for now

Optionally, we can add a confirmation notification on change.
