### ISSUE TITLE
logout problems with staging/local

### ISSUE THREAD

**Issue by PierreBrethes** [Zenika/skillZ#332]
In staging or local, when a user logout, the logout seems not to work. It refreshes the page but sometimes you can still see your profile on the top bar.

**Comment by benjaminbrgs** [comment]
It's working in staging. What's the issue exactly ?

**Comment by MailyLehoux** [comment]
Meme problème chez moi. Quand je clique sur déconnecter ça rafraîchis ma page, et je ne vois donc pas cette page là (comme pour la prod) : 
![Capture d’écran de 2022-11-15 09-45-01](https://user-images.githubusercontent.com/85115963/201872277-4a3046b4-012d-4ca2-b54c-eede7601e7bd.png)

**Comment by benjaminbrgs** [comment]
Ok I was able to reproduce it!
It seems it's only happen when you only have one google account connected.

**Comment by MailyLehoux** [comment]
That's strange, I have 2 accounts connected but yes sometimes it's working but sometimes not 🧐

**Comment by MailyLehoux** [comment]
I can't find any anomaly from the code. So it could come from the auth0 parameters? 

-> _"Ensure that you have your domain url as an “allowed logout URL” in your auth0 application settings. "_

I don't know if we have several apps for each env in auth0. If we have just one, the problem is not the settings. Do you have infos about this @benjaminbrgs ?

**Comment by benjaminbrgs** [comment]
Unfortunately, I'm pretty sure there is only one Auth0 App for all environments..
Do you know if you have this issue before this commit : https://github.com/Zenika/skillZ/commit/ff3d8160c9c5028ae8d4b1c0ae113011c52c1e76 ?

**Comment by MailyLehoux** [comment]
Yes at this commit I can log out properly : 
`git checkout a5aa794cfed4ae0d89c8c7febb149b984c9c8d60` 

And the issue occurs at the head ff3d8160c9c5028ae8d4b1c0ae113011c52c1e76
