### ISSUE TITLE
La réunion doesn't exist in staging 

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#338]
/zenika 

![Capture d’écran de 2022-11-16 10-46-03](https://user-images.githubusercontent.com/85115963/202146692-e68b71f9-b2c3-4a80-8cd0-aed1e4494c02.png)

**Comment by MailyLehoux** [comment]
https://github.com/Zenika/skillZ/pull/294 PR associated ?

**Comment by benjaminbrgs** [comment]
> #294 PR associated ?

This PR removes the translation and uses the name directly from the Database.
We have to add `La Réunion` in database. How do we proceed, with seeder or with the admin console ?

**Comment by MailyLehoux** [comment]
Yes ! Indeed the issue don't come from the PR. La réunion was on seeds folder. I don't know why the agency migration has no effect in staging. I'm trying with admin console. let's see :hankey:
