### ISSUE TITLE
Admin modal to approve

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#351]
As admin I would see a modal when I click on "approve" in order to modify a skill before submitting 

Rules : 

We can't click on approve if no topic are mentionned

#PIERRE-EDIT 23/11/22

1. le "Approuver" d'un skill ouvre une modal qui prend le formulaire du skill, pour que l'admin puisse le modifier avant de l'approuver. Renommer le bouton "Approuver" en "Vérifier"
2. Pour l'utilisateur comme pour l'admin, le formulaire bloque si il n'y a pas au moins un topic.
3. La description d'un skill doit obligatoire. Afficher un message pour indiquer qu'elle doit etre en anglais tant que l'internationalisation côté back n'est pas prête.

**Comment by PierreBrethes** [comment]
Should we block when a user creates a skill without topic ? Or can't approve as an admin if no topic ?

**Comment by MailyLehoux** [comment]
For me it's both

**Comment by benjaminbrgs** [comment]
I'd say optional for a user and required for admin ?

**Comment by MailyLehoux** [comment]
I think we should split this issue into 2 parts : 
- the admin modal that requires topics 
- a new section on the create skill modal that allow user to add topics. Actually we have anything to allow the user to modify skill information

For this issue I suggest to focus on the admin modal only

**Comment by benjaminbrgs** [comment]
> I think we should split this issue into 2 issues :
> 
> * the admin modal that requires topics
> * a new section on the create skill modal that allow user to add topics.
> 
> Actually we have anything to allow the user to modify skill information
> 
> For this issue I suggest to focus on the admin modal only

I agree ! This admin modal is more important
