### ISSUE TITLE
Clickable skill panels

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#362]
As user I would know that the skill panels are clickable. 

A hover can be good 
![Capture d’écran de 2022-11-23 10-36-10](https://user-images.githubusercontent.com/85115963/203513662-bafbf094-23f5-4c9e-b66a-b093096d63b4.png)

**Comment by ThomG317** [comment]
@MailyLehoux I notice that skill panel are not the only element without and hover or an active style, would it be ok if I check the overall app ? (And maybe adjust a bit the issue title)

**Comment by MailyLehoux** [comment]
Yes @ThomG317 :+1:
