### ISSUE TITLE
Add a title for the 5 best notes of skills

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#365]
As a user I want to see a title for the classment of my 5 best skills in order to know what this section means

![Capture d’écran de 2022-11-23 11-44-25](https://user-images.githubusercontent.com/85115963/203527323-dfbc511e-eb13-438b-a9c4-7029758007be.png)

**Comment by ThomG317** [comment]
@MailyLehoux I tried to improvise a little on this, I'd like to check the visual for approbation before creating the PR.

![image](https://user-images.githubusercontent.com/62474391/203530954-81d62ed4-e45b-42f0-8c0b-22b4adcc6cc0.png)

**Comment by MailyLehoux** [comment]
I think you can also add an icon like 🏆 But yes I like this :+1:

**Comment by MailyLehoux** [comment]
Yes ok. We use svg for the specials icons but [react icons](https://react-icons.github.io/react-icons/) for the "basics" icons. I love the star icon as wll :+1: I didn't know about the svg as font it seems very interesting for Skillz it's true that I often struggle with svg
