### ISSUE TITLE
Better understanding of graphs axes

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#366]
On home page

as user I want to defferentiate the abscissa and ordonates axes in order to understand the position of the bullets 

Maybe add arrows to understand the coordinates, and the directions. Also add a legend for the abscissa and ordinates (like in /[category] we have "desire level" and "skill level"

![Capture d’écran de 2022-11-23 11-46-27](https://user-images.githubusercontent.com/85115963/203527805-050dd952-56d4-49e5-a90b-144f9518f62d.png)

**Comment by ThomG317** [comment]
@MailyLehoux I did a few modification to try and implement it, here a screenshot:

![image](https://user-images.githubusercontent.com/62474391/203575357-0576a9d6-e2d2-4185-a43b-fc61f44699bf.png)

**Comment by MailyLehoux** [comment]
I don't know if the others have suggestions, but for me it's clearer like this :v:
