### ISSUE TITLE
Admin modify description of a category

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#369]
**As admin I would see a new section on the admin page with the several categories in order to modify the description of a category**

I suggest to add a "soft" sentence to remind the administrators to enter the description in english

**Comment by benjaminbrgs** [comment]
Current description to add : 
- Practices: Know-how related to the usage of a tool, framework or methodology
- Knowledge: Theoretical or applicable knowledge of a concept, a field of expertise or a general competency (e.g. a spoken language)
- Activities: Services that can typically be delivered to our clients and which progress can be tracked (i.e. they have identifiable phases)
- Behavior: Strengths and general postures defining our capabilities to actively interact with others
