### ISSUE TITLE
Can't scroll the list of certifications

### ISSUE THREAD

**Issue by gfeun** [Zenika/skillZ#418]
I want to add a certification to my profile.
However I can't scroll over the certification list to find the proper certification.

I access the certification page:
![image](https://user-images.githubusercontent.com/32910236/207803710-14ea9837-33df-4c8b-91b6-8b83d428f3c5.png)

When i scroll over the certs, the background scrolls but not the certifications:
![image](https://user-images.githubusercontent.com/32910236/207803672-f77fb348-21dd-4803-b62e-b795b796702f.png)

I'd also like to be able to leave the modal by clicking outside. At the moment i have to click the cancel button which is counterintuitive to the modals i'm used to on other sites.

I'm on Firefox 108.0

**Comment by jeanphibaconnais** [comment]
Hello @gfeun , thanks for this report ! I set a high priority on this issue.

**Comment by benjaminbrgs** [comment]
Fixed by https://github.com/Zenika/skillZ/issues/401
