### ISSUE TITLE
Depreciation on Mobile view

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#575]
In production, the side menu in the mobile view has desapeared : 

![Capture d’écran de 2023-02-27 10-52-03](https://user-images.githubusercontent.com/85115963/221531172-77988cd8-8644-49a7-9a45-13af633d86a9.png)

Click on profile pic to reproduce

**Comment by benjaminbrgs** [comment]
The sidebar has been removed in https://github.com/Zenika/skillZ/pull/501
