### ISSUE TITLE
Different graph representations for same data

### ISSUE THREAD

**Issue by nkCreation** [Zenika/skillZ#65]
Between the add page and the display page, I have two different graphs - I should have the same representation I think because it's the same data ?

![image](https://user-images.githubusercontent.com/4450152/117677827-197dcc80-b1af-11eb-8e80-170917e3af2e.png)
![image](https://user-images.githubusercontent.com/4450152/117677904-2b5f6f80-b1af-11eb-9f52-53607d7d4f6c.png)

**Comment by MailyLehoux** [comment]
These graphs has been refacto. We did not noticed any similar problems. I'll close this issue, pleace tell us if you have any problem
