### ISSUE TITLE
Change scale labels

### ISSUE THREAD

**Issue by Ked57** [Zenika/skillZ#69]
level:

 - Je ne connais pas
 - J'ai entendu parler / J'ai juste testé rapidement
 - Je l'ai déjà utilisé
 - Je suis autonome
 - Je suis expert / Je peux former

desire

 - Je ne veux plus l'utiliser / Je ne veux pas apprendre
 - Je préfère éviter / Seulement pour dépanner
 - Je n'adore pas mais ca ne me dérange pas
 - J'aime beaucoup
 - Je veux l'utiliser tous les jours

**Comment by anthonylegoas** [comment]
Proposition pour le `level`, partant du constat que personnellement je ne vais pas renseigner une compétence que je ne connais pas du tout (à minima je me suis intéressé au sujet pour savoir ce que c'était, sinon je ne suis pas capable de me positionner sur le niveau d'appétence 🤔 ) :

- J'ai regardé ce que c'était
- J'ai joué avec (J'ai testé)
- J'ai bossé avec sur des projets significatifs
- J'ai bossé avec, je maitrise bien, j'ai creusé le fonctionnement (formateur?)
- J'ai beaucoup bossé avec dans des contextes différents, je connais parfaitement
