### ISSUE TITLE
[Idea]: semantic versionning and auto changelog

### ISSUE THREAD

**Issue by nkCreation** [Zenika/skillZ#70]
# Idea

With the help of few tools and packages it could be great to have a changelog base on the commit message ?

with husky, commit-lint, commitizen for example.

**Comment by coyotte508** [comment]
Gitmojis now support versioning (feature = minor, breaking change = major, a lot of others = patch) in their `gitmoji.json` so it would be really cool. And it would be possible to also group change logs by gitmoji: "New features", "Bug fixes", ...

It could almost be a separate project / module reusable across many zenika projects

**Comment by hgwood** [comment]
Could you describe a little further? eg A changelog for who? Why?

**Comment by MailyLehoux** [comment]
Could be nice to integrate lint on the project. And maybe add husky later.
