### ISSUE TITLE
Skill anecdote

### ISSUE THREAD

**Issue by MailyLehoux** [Zenika/skillZ#82]
Some anecdotes can be fill by us

All skills with no anecdote can be modified by the user, with a hover component on the anecdote sentence

Notify the administrator for each tech added on the app, with the possibility to change the anecdote and the name of the skill

This concept can be possible ?

**Comment by Ked57** [comment]
What do you mean by anecdote ?

**Comment by MailyLehoux** [comment]
For example, for the skill "C" the sentence could be : " C was originally developed for use with the Unix operating system, which is largely written in C, so part of the success of the language is due to the acceptance of Unix". 

It could be a funny or a historic anecdote of the skill selected

**Comment by Ked57** [comment]
This could be nice indeed ! What do you think @ebriand ?

**Comment by ebriand** [comment]
This is a good idea 👍 It is again a feature to add to an admin interface 😄

**Comment by mcampourcy** [comment]
Love it !
Maybe we could do a first shot, without admin rights ? Anyone can create/edit/delete an anecdote ?

**Comment by MailyLehoux** [comment]
Yes I think it can be good like this👍
