### ISSUE TITLE
No profiles shown when filtering by skill

### ISSUE THREAD

**Issue by ClementVanPeuter** [Zenika/skillZ#94]
No profiles shown when filtering by a particular skill.

E.g: https://skillz.zenika.com/fr/skills/zenika/languages-and-frameworks?agency=Nantes

When we click on the "Java" Skill we've got no data shown.

On this page ( https://skillz.zenika.com/fr/skills/zenika/languages-and-frameworks/Java%20%E2%89%A47?agency=Nantes) we loose the ability to show some profiles.

**Comment by Ked57** [comment]
This was fixed in staging, will be in prod soon. Thanks @ClementVanPeuter !
