### ISSUE TITLE
Create a slack bot to remind users to update skills and desires

### ISSUE THREAD

**Issue by ebriand** [Zenika/skillZ#98]
- [ ]  setup a github repo to create a "hello world" bot
- [ ] Add in profile a checkbox about bot notifications
- [ ] make the bot introduce itself to users and ask if they want to be notified regularly about skillZ. Example : "Hi, I am skillZ bot, do you want me to remind you about skillZ regularly ?"
- [ ] Make the bot ping the user about random apetites and ask if the user has skilled up
- [ ] add a bot command, example "/skillz angular" to directly add a skill and apetite in slack

**Comment by Ked57** [comment]
I'm wondering if the next API can be used instead of having to host another app

**Comment by ebriand** [comment]
I think we should have a separate project because the bot will have a different lifecycle that the skillz app.
